### ISSUE TITLE
Propose creating design/research related labels

### ISSUE THREAD

**Issue by ei8fdb** [ownpass/ownpass#16]
Hi!

In order to highlight design (logo, graphic, ui, interaction) and user research work thats needed I'd like to propose the creation of some tags:
- design
- research
- paper cuts/junior jobs

If there is a lot of design and research work it may be necessary to spilt out the "design" and "research" labels as above, but for the moment lets see how it goes.

The paper cut usability bugs label was developed by David Siegel, then on the user experience team at Canonical:

> […] a paper cut is a bug that will improve user experience if fixed, is small enough for users to 
> become habituated to it, and is trivial to fix.

(As described in [Jan Borchardt usability in free software](http://jancborchardt.net/usability-in-free-software#Identify-paper-cuts))

Any thoughts? Suggestions and opinions please!

**Comment by waltertamboer** [comment]
We have several repositories now. Repositories for the browser extensions and @kwarkjes made a new control-panel repository. This OwnPass repository is simply the API and we might need to rename it later on.

Since this is only the API, in theory usability related issues would not be reported here but instead in their own repository (issue related to project/repo).

Would it make sense to add the labels to the following repositories? Meaning that we move issues to their correct project as well.
- https://github.com/ownpass/control-panel
- https://github.com/ownpass/chrome-extension
- https://github.com/ownpass/firefox-extension
- https://github.com/ownpass/ie-extension
- https://github.com/ownpass/ios-app
- https://github.com/ownpass/android-app

**Comment by ei8fdb** [comment]
@waltertamboer I agree. Makes more sense to have those labels in those repos.

If you want I can make those labels in each repo? 

I can then tie them back to the design-research repo [README.md](https://github.com/ownpass/design-research/blob/master/README.md) so people can find them?

**Comment by waltertamboer** [comment]
Yup perfect, go nuts :)
